name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install pygame pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller --noconsole --onefile launcher.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MojLauncherEXE
        path: dist/launcher.exe
